name: Tests

on: [ pull_request, push ]

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install ocla
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[tests]
      - name: Run tests
        run: |
          black --check .
          isort --check .
          # Run pylint in two stages: (1) regular files, (2) tests.
          pylint --ignore="__version__.py" --ignore-patterns=".*_test\.py" model_calibration
          pylint --disable="missing-function-docstring" model_calibration/**/*_test.py
          pytype

  test_ocla:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ocla
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[tests]
      - name: Run tests
        run: |
          pytest -vv

  test_jupyter:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ord_schema
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install .[examples,tests]
      - name: Test notebooks
        run: |
          treon
